# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/dotnet/format
    rev: "v8.0.453106"
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format dfs/dfs.sln --diagnostics "" -v normal --include
        files: ^dfs/.*
        types_or: ["c#", "vb"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
