# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Project build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Restore dependencies
        run: dotnet restore dfs/dfs.sln

      - name: Build .NET
        run: dotnet build --no-restore dfs/dfs.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal dfs/dfs.sln

      - uses: actions/checkout@v4
      - name: Test UI
        working-directory: ./dfs/electron
        run: |
          npm ci
          npm run package-debug
          npm test
