# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Project build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - uses: actions/checkout@v4
      - name: Run UI tests
        working-directory: ./dfs/ui
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore dfs/dfs.sln

      - name: Build .NET
        run: dotnet build --no-restore dfs/dfs.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal dfs/dfs.sln
